baseURL = '/'
languageCode = 'en-us'
title = 'johnmcostaiii.com'
theme = 'prav'
disqusShortname = "johnmcostaiii"

[params]
    title = "johnmcostaiii.com"
    tagline = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    author = "John M Costa, III"
    authorImgPath = "/img/author.png"
    authorBlurb = "Father, Husband, Amateur Athlete, Aspiring Gardener, Outdoor Enthusiast"
    features = ["posts", "comments"]


[social]
  email = "mailto:john.costa@gmail.com"
  facebook = "https://www.facebook.com/johnmcostaIII/"
  twitter = "https://twitter.com/johncosta"
  github = "https://github.com/johncosta"
  linkedin = "https://www.linkedin.com/in/johnmcosta/"
