baseURL = '/'
languageCode = 'en-us'
title = "johnmcostaiii.com"
theme = 'prav'
disqusShortname = "johnmcostaiii"
googleanalytics = "UA-24469699-1"
enableRobotsTXT = true

[server]
    [[server.headers]]
        for = '/**'
        [server.headers.values]
            Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
            Content-Security-Policy = "default-src 'self' *.johncosta.com"
[params]
    title = "johnmcostaiii.com"
    tagline = "Engineering Leadership and Software Development"
    author = "John M Costa, III"
    authorImgPath = "/img/author.png"
    authorBlurb = "Father, Husband, Amateur Athlete, Aspiring Gardener, Outdoor Enthusiast"
    features = ["posts", "comments"]


[social]
  email = "mailto:john.costa@gmail.com"
  facebook = "https://www.facebook.com/johnmcostaIII/"
  twitter = "https://twitter.com/johncosta"
  github = "https://github.com/johncosta"
  linkedin = "https://www.linkedin.com/in/johnmcosta/"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
