[server]
    [[server.headers]]
        for = '/**'
        [server.headers.values]
            Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
            Content-Security-Policy = "default-src 'self' *.johncosta.com"
